### ISSUE TITLE
central control

### ISSUE THREAD

**Issue by jmnote** [kuoss/ingress-annotator#38]
central control

```yaml
rules:
- description: admin-auth
  selector:
    include: "admin"  # Targets all Ingresses within the 'admin' namespace.
    # exclude: ""  # Default: No exclusions (an empty string implies all resources are included).
  annotations:
    # Redirects unauthenticated users to the OAuth2 authentication page, passing the original request URL for redirection after login.
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.example.com/oauth2/start?rd=https://$host$request_uri
    # Specifies the URL used to validate user authentication status.
    nginx.ingress.kubernetes.io/auth-url: https://oauth.example.com/oauth2/auth

- description: restrict-access-except-public
  selector:
    # include: "*"  # Default: Includes all Ingresses (wildcard matches every namespace and name).
    exclude: "frontend/landing-page,dashboard/public-status" # Excludes specific Ingresses: the 'landing-page' in the 'frontend' namespace and the 'public-status' in the 'dashboard' namespace.
  annotations:
    # Restricts access to only the specified IP ranges (whitelist).
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/16

- description: api-secure-mtls
  selector:
    include: "api/*"  # Targets all Ingresses within the 'api' namespace.
    exclude: "api/internal,api/debug"  # Excludes specific Ingresses: 'internal' and 'debug' within the 'api' namespace.
  annotations:
    # Enables mutual TLS authentication for API Ingresses to ensure secure and authenticated communication.
    nginx.ingress.kubernetes.io/auth-tls-secret: "api/mtls-secret"

- description: throttle
  selector:
    include: "*/throttle-*,*/*-throttle"  # Targets all Ingresses with names starting with 'throttle-*' or ending with '-throttle' across all namespaces.
  annotations:
    # Limits the request rate to 10 requests per second.
    nginx.ingress.kubernetes.io/limit-rate: "10"
```
