### ISSUE TITLE
Support List Format for Annotation Values

### ISSUE THREAD

**Issue by jmnote** [kuoss/ingress-annotator#40]
Support List Format for Annotation Values

```yaml
annotations:
  nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16,192.168.0.1"
```
```yaml
annotations:
  nginx.ingress.kubernetes.io/whitelist-source-range:
  - 10.0.0.0/16
  - 192.168.0.1
````
